require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'

Layout/LineLength:
  Max: 120
  AllowedPatterns: ['\A\s*#']

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true